version: '3'

services:
  service-api-db:
    image: postgres:10.9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: service_api_local

  service-api-app:
    container_name: service-api-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8888
    links:
      - service-api-db
    environment:
      - DATABASE_URL=postgres://postgres:password@service-api-db/service_api_local
